pipeline {
    agent {
        kubernetes {
          defaultContainer 'ubn20-nodejs16-java11'
          yaml buildpack(
            pack(name: "ubn20-nodejs16-java11", version: "stable"),
            pack(name: "ubn20-dind-mvn3-java11", version: "stable"),
            pack(name: "alpine-dind", version: "stable"),
            pack(name: "ubn20-awssso-python3", version: "stable")
          )
        }
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
